### ISSUE TITLE
Link zu www.govdata.de in Github Settings

### ISSUE THREAD

**Issue by tordans** [GovDataOfficial/GovDataPortal#2]
Es wäre super, wenn auf der Github-Projekt-Startseite direkt ein Link zu https://www.govdata.de/ stehen würde.
Das geht in den Settings und erscheint dann hier:
<img width="585" alt="bildschirmfoto 2018-03-24 um 11 00 41" src="https://user-images.githubusercontent.com/111561/37862766-d1c4f800-2f52-11e8-9765-99bc56f9381f.png">

In dem Zuge könntet ihr auch _Wiki_ und _Projects_ deaktiveren, die scheinbar in diesem Git-Repo nicht verwendet werden. Dann muss man sie nicht erst anklicken um das zu sehen :).

**Comment by seitenbau-govdata** [comment]
Vielen Dank für die Anmerkungen. Ist erledigt. :-)
