### ISSUE TITLE
build out of the box

### ISSUE THREAD

**Issue by stbischof** [GovDataOfficial/GovDataPortal#5]
if i rum mvn package i got some issues:

`opendataregistry-client/pom.xml`
 is missing

```
<dependency>
    <groupId>javax.xml.bind</groupId>
    <artifactId>jaxb-api</artifactId>
    <version>2.3.1</version>
</dependency>

```

and `de.seitenbau.serviceportal:gui-common:jar:1.27.1` is not in the given dependencies

[ERROR] Failed to execute goal on project portlet-common: Could not resolve dependencies for project de.fhg.fokus.odp:portlet-common:jar:3.8.0: Could not find artifact de.seitenbau.serviceportal:gui-common:jar:1.27.1 in maven2-repository.dev.java.net (http://download.java.net/maven/2/) -> [Help 1]

**Comment by seitenbau-govdata** [comment]
@stbischof Thanks for start building the maven project. 😃 

First I would like to make a hint that the code on GitHub is currently not up-to-date and is still based on Liferay 6. We already have updated the project to Liferay 7, but haven't updated the GitHub repo, yet. We'll update the repository on GitHub soon.

Yes, you're right that some dependencies are not available at a official public maven repository. The required dependencies are in the folder [local-maven-repo](https://github.com/GovDataOfficial/GovDataPortal/tree/master/local-maven-repo) in the repository. Currently these are no more related within the maven build process, so you have to copy the folders manually in your local maven repo before building the maven project.

Please describe the problem in more detail (e.g. by adding messages from standard output) you have with the dependency `jaxb-api` in the module `opendataregistry-client`.

**Comment by stbischof** [comment]
I Would really like to see an an updated version of the `gov-data-poral` on `github` or an other open source repository.

**Comment by seitenbau-govdata** [comment]
@stbischof Please note that the source code was recently updated. The Liferay portlets are compatible with Liferay 7 now.

**Comment by seitenbau-govdata** [comment]
Closing issue after the reported issue is solved and getting no response on the last comment for 5 months.
